### ISSUE TITLE
General refactoring

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/bandada#187]
**Tasks**:

- [x] Fetch on-chain/off-chain in parallel
- [x] Bump Semaphore version
- [x] Create a hook for sessions
- [x] Types
- [x] Names & HTML
  - [x] Pages
  - [x] Components
- [x] Add comments
