### ISSUE TITLE
Revamping UI with new M3 designs

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/bandada#192]
**Tasks**:

- [x] Revamp home page UI
- [x] Revamp groups page UI
- [x] Revamp group page UI
