### ISSUE TITLE
OAuth API: Twitter

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/bandada#202]
**Tasks**:

- [x] Make OAuth utils functions easily extendable ([ref](https://github.com/privacy-scaling-explorations/bandada/pull/214#discussion_r1231772516))
- [x] Integrate Twitter flow in `reputation` dashboard route
- [x] Integrate Twitter flow in `reputation` API controller

**Comment by 3pwd** [comment]
Hey, I was just looking around...
For zkitter I had to do just that back then. 
I chose to use [passport.js](http://www.passportjs.org/). It has lot of different on the shelf "strategies", so new oauth providers becomes very easy to add.
The alternative...implementing an oauth workflow manually is a pain...

Based on my experience with oauth with zkitter, I would recommend going down the passport road to implement your Oauth API 😉
Will make your life easier

https://github.com/zkitter/zkitterd/blob/main/src/services/http/controllers/Auth.ts

☝️ applies to #203 too

**Comment by cedoor** [comment]
Hey @3pwd, we were using it for the old authentication system in the admin dashboard, until we decided to use SIWE instead.

This API is actually a flow to get the access token and validate reputation. I think we can keep it light. Something like:

1. Clients use this API
2. This API redirects to the Twitter page to allow users to accept our auth requests
3. That Twitter page redirects to a Bandada callback URL, which gets the access token and validates user's reputation
4. That callback URL eventually redirects to the client web app
